# -*- coding: utf-8 -*-
"""python basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AiYH5lsxyys85h7hNNF_5doWfpzyQLSZ
"""

5*5

a = 10

1+1

a

a

sudh = 20

sudh

a+sudh

type(a)

type(sudh)

b = 2.09

type(b)

c = 45.23345

type(c)

d = "sudhanshu"

type(d)

e = 'this is my first tech class'

type(e)

n = True

type(n)

m = False

type(m)

n+m

True * True

True * False

True / False

1 /0

sudh = 5 + 8j

type(v)

sudh.real

sudh.imag

sudh

print("my name is sudhanshu")

print(a)

print(sudh)

s = "pwskills"

type(s)

s[0]

s[2]

s[3]

s[-1]

s[-8]

s[0:3]

s[0:2]

s[0:4]

s[0:8:2]

s[0:4:1]

s[::2]

s[0::2]

s[2::2]

s[2::1]

s[::-1]



s

s[2:7:-1]

s[8:0]

s[8::-1]

s[-2 : -8 : -1]

s[-2 : : -1]

s[::-1]

s[::]

s[:-90:]

s[90]

s[:-90000:-1]

c = 200

s1 = "this is my string class"

len(s1)

s1.find('s')

s1.find('i')

s1.find("is")

#this is a code to find a charecterd of sub string in string
s1.find("iS")

s1.count('s')

s1

s1.count("st")

s1.count('z')

s1

s1.upper()

s2 = 'THIS IS MY STRING CLASS'

s2

s2.lower()

s1

s1.title()

s1.capitalize()

s

s + 1

s + " sudh"

s + '1'

s+ str(1)

s * 3

'sudh' *4

"sudh" / 4

"don't do copy and paste in my class"

'don"t do copy and paste in my class'

s3 = """This is my first class for programming
i have leant variable declaration , data type , string , int , boolean , complex number
i have seen some example of string slicing and indexing
i have gone though some of the string inbuilt function
apart from that i am trying to practice in my system
but some of us in our calss are not executing code and still they are answering which is bad """

s3

s

s[::-1]

s[-8::-1].upper()

s = "rohan"

s

print(s)

s[-2::-1]

s = "pwskills"

s[-2::-1]

s4= """Iam praharshitha
im in second year
i want to learn python"""

s4

s[:-8:-1]

s

s * 3

s = "pwskills "

s*3

a = 1

b = 3
c = 5

s

s = 'myskill'

s[-2::-1]

# jkfhsajasf
# fasdfhiasfhd
# ihasdufh
# iuhasdfias
# hoasdofasf
# hiuohasdofs
# hlohasfdsa

s = "pwskill"

s[2:3:1]

a = 10

a





















